### ISSUE TITLE
Belgische Smart Meter

### ISSUE THREAD

**Issue by vdborght** [XiloXL/Powerbaas#5]
Beste,

Voor de Belgische Smart meter zijn er blijkbaar een aantal dingen anders:

1.8.1 = Piekverbruik (niet "Low")
1.8.2 = Dalverbruik (niet "High")
2.8.1 = Piek injectie (niet "Low")
2.8.2 = Dal injectie (niet "High")

Gas wordt bij ons weergegeven in 24.2.3 met de sscanf filter "0-1:24.2.3(%ldW)(%f*m3" 
Ook in België kan je beter niet afgaan op de wattage, want dan zou ik sinds de installatie van mijn slimme meter (2 maanden geleden) 220 gigawatt verbruik hebben in 766m3 ;-) 

mvg,
Peter

**Comment by XiloXL** [comment]
Dag Peter, 

Hartelijk dank voor uw feedback. 
We gaan een update maken voor de Belgische variant.
Kun je nog vertellen welke meter u heeft, merk en type?

Met vriendelijke groet,

Powerbaas.nl

**Comment by vdborght** [comment]
Beste,

Ik heb een Siconia T211, maar misschien beter is om deze presentatie van
Fluvius door te nemen:
https://partner.fluvius.be/sites/fluvius/files/2020-01/dmk-demo-v2.1-rtc.pdf

Voor mezelf trouwens geen update nodig, ik heb zelf jullie code al
aangepast voor mijn library ;-)
Voor de volgende Belgische gebruiker zou het uiteraard wel handig zijn.

Note: Die presentatie van Fluvius vind ik zelf ook maar net en daardoor
merk ik dat bij de gasmeter W niet staat voor "Watt", maar voor "Winter"...
weer iets bijgeleerd :-)

Groetjes,
Peter

Peter Vanderborght
***@***.***
+32-499-123.979

**Comment by vdborght** [comment]
Nog een kleine extra opmerking:
Als je automatisch de meter/standaard zou willen identificeren aan de hand
van het datagram, merk dan op dat de versie van de standaard in mijn meter
anders is, maar de "Fluvius" identificatie wel dezelfde:

   - Uit het document:
      - /FLU5\253769484_A
      - 0-0:96.1.4(50213)
      - Mijn meter:
      - /FLU5\253769484_A
      - 0-0:96.1.4(50216)


Groetjes,
Peter

Peter Vanderborght
***@***.***
+32-499-123.979

**Comment by XiloXL** [comment]
Dag Peter,

We hebben ondertussen een nieuwe release ingediend, v1.2.0, hierin zit auto-detectie voor Belgische meters. 
Zou je zodra de release beschikbaar is, willen testen of het werkt voor jouw meter?

Met vriendelijke groet,

Gerard Oudenampsen
Powerbaas.nl

**Comment by vdborght** [comment]
Hallo Gerard,

Geen probleem, ik kijk wanneer hier tijd voor vind.

Groetjes,
Peter

Peter Vanderborght
***@***.***
+32-499-123.979

**Comment by vdborght** [comment]
Beste Gerard,

Er is wat tijd over gegaan, maar ik kan bevestigen dat de nieuwe versie de
Belgische meter correct detecteert en juiste waarden teruggeeft

Groetjes,
Peter

Peter Vanderborght
***@***.***
+32-499-123.979

**Comment by XiloXL** [comment]
Super! Dan ga ik hem afsluiten. Bedankt!
