### ISSUE TITLE
Error in file SmartMeterLineParser.cpp

### ISSUE THREAD

**Issue by douweyntema** [XiloXL/Powerbaas#6]
In file SmartMeterLineParser.cpp there are 2 typos on line 60 and 63. This should be:
Line 60:     meterReading.voltageL2 = result;
Line 62    meterReading.voltageL3 =  result;

Addidion:
For making the current readout working, change the file MeterReading.h line 31,32, 33 should be declared as float. And in file SmartMeterLineParser.cpp lines 46, 49,52 remove the INT function.

**Comment by XiloXL** [comment]
Thanks, and merged!
